# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  def current_version
    get_version_number(target: "Baltic Amadeus iOS Task")
  end

  def ipa_build_number
    get_ipa_info_plist_value(ipa: 'Baltic Amadeus iOS Task.ipa', key: 'CFBundleVersion')
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "Baltic Amadeus iOS Task.xcodeproj")
    build_app(scheme: "Baltic Amadeus iOS Task")
    upload_to_testflight
  end

  lane :build do
    build_app(scheme: "Baltic Amadeus iOS Task")
  end

  lane :tests do
    run_tests(scheme: "Baltic Amadeus iOS Task")
  end

  lane :release do 
    set_github_release(
      repository_name: "srini2dl/baltic-amadeus-ios-task",
      api_token: ENV["GITHUB_TOKEN"],
      name: "v" + current_version,
      tag_name: "v" + current_version,
      description: (File.read("changelog") rescue "No changelog provided"),
      commitish: "main",
      upload_assets: ["Baltic Amadeus iOS Task.ipa"]
      )
  end
end
