name: Realse and Testflight distrubution

on:
  workflow_dispatch:
  
jobs:
  build:
    name: Release
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Unit Test
        run: bundle exec fastlane tests
      
      - name: Testflight upload
        run: bundle exec fastlane beta
        
      - name: Release
        run: bundle exec fastlane release
        
